version: "3.8"

services:
  immich-server-1:
    container_name: immich_server_1
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2283:3001
    volumes:
      - type: bind
        source: ${UPLOAD_LOCATION}
        target: /usr/src/app/upload
      - /home/eduardo/Documents/para_incluir:/usr/src/app/old_backup
    env_file:
      - stack.env
    depends_on:
      - redis-1
      - database-1

    restart: always



  immich-machine-learning-1:
    container_name: immich_machine_learning_1
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:

      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis-1:
    container_name: immich_redis_1
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database-1:
    container_name: immich_postgres_1
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
